#! /bin/bash
echo "wprowadź początkowy adres IP:"
read FirstIP

echo "wprowadz ostatni oktet ostatniego adresu IP:"
read LastOctetIP

echo "Wprowadz numer szukanego portu: "
read port

nmap -sT $FirstIP-$LastOctetIP -p $port >/dev/null -oG MySQLscan

cat MySQLscan } grep open > MySQLscan2

cat MySQLscan2
